run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable:
      - shadow
  errcheck:
    exclude-functions:
      - fmt:.*
  staticcheck:
    checks:
      - all
      - -ST1000
      - -ST1003
      - -ST1016
  gosec:
    excludes:
      - G204

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - revive
    - gofmt
    - goimports
    - whitespace
    - unparam
    - nilerr
    - prealloc
    - dogsled

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0